# Dedicated to the public domain under CC0: https://creativecommons.org/publicdomain/zero/1.0/.

from dis import opmap


CALL_FUNCTION         = opmap['CALL_FUNCTION']
COMPARE_OP            = opmap['COMPARE_OP']
DELETE_FAST           = opmap['DELETE_FAST']
DUP_TOP               = opmap['DUP_TOP']
END_ASYNC_FOR         = opmap['END_ASYNC_FOR']
EXTENDED_ARG          = opmap['EXTENDED_ARG']
FOR_ITER              = opmap['FOR_ITER']
JUMP_ABSOLUTE         = opmap['JUMP_ABSOLUTE']
JUMP_FORWARD          = opmap['JUMP_FORWARD']
JUMP_IF_FALSE_OR_POP  = opmap['JUMP_IF_FALSE_OR_POP']
JUMP_IF_NOT_EXC_MATCH = opmap['JUMP_IF_NOT_EXC_MATCH']
JUMP_IF_TRUE_OR_POP   = opmap['JUMP_IF_TRUE_OR_POP']
LOAD_ASSERTION_ERROR  = opmap['LOAD_ASSERTION_ERROR']
LOAD_CONST            = opmap['LOAD_CONST']
LOAD_FAST             = opmap['LOAD_FAST']
LOAD_GLOBAL           = opmap['LOAD_GLOBAL']
POP_BLOCK             = opmap['POP_BLOCK']
POP_EXCEPT            = opmap['POP_EXCEPT']
POP_JUMP_IF_FALSE     = opmap['POP_JUMP_IF_FALSE']
POP_JUMP_IF_TRUE      = opmap['POP_JUMP_IF_TRUE']
POP_TOP               = opmap['POP_TOP']
RAISE_VARARGS         = opmap['RAISE_VARARGS']
RERAISE               = opmap['RERAISE']
RETURN_VALUE          = opmap['RETURN_VALUE']
SETUP_ASYNC_WITH      = opmap['SETUP_ASYNC_WITH']
SETUP_FINALLY         = opmap['SETUP_FINALLY']
SETUP_WITH            = opmap['SETUP_WITH']
STORE_FAST            = opmap['STORE_FAST']
WITH_EXCEPT_START     = opmap['WITH_EXCEPT_START']
YIELD_FROM            = opmap['YIELD_FROM']
YIELD_VALUE           = opmap['YIELD_VALUE']